[project]
name = "frontend-p34"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "fastapi>=0.117.1",
    "uvicorn>=0.36.0",
]
